//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promasy.Modules.Orders.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderExporter_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderExporter_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Promasy.Modules.Orders.Resources.Services.OrderExporter.uk", typeof(OrderExporter_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-який.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затверджую.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класифікатор.
        /// </summary>
        internal static string Classifier {
            get {
                return ResourceManager.GetString("Classifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовник.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Співробітник з обов&apos;язковою роллю {0} відсутній.
        /// </summary>
        internal static string Employee_with_required_role__0__is_missing {
            get {
                return ResourceManager.GetString("Employee with required role {0} is missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cформоване.
        /// </summary>
        internal static string Generated_on {
            get {
                return ResourceManager.GetString("Generated on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to з.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис замовлення.
        /// </summary>
        internal static string Order_description {
            get {
                return ResourceManager.GetString("Order description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовлено.
        /// </summary>
        internal static string Ordered {
            get {
                return ResourceManager.GetString("Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовлення за категорією.
        /// </summary>
        internal static string Orders_of_type {
            get {
                return ResourceManager.GetString("Orders of type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аркуш.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можливий виробник та кат. номер.
        /// </summary>
        internal static string Possible_producer_and_cat_no {
            get {
                return ResourceManager.GetString("Possible producer and cat no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можливий постачальник.
        /// </summary>
        internal static string Possible_supplier {
            get {
                return ResourceManager.GetString("Possible supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна одиниці.
        /// </summary>
        internal static string Price_of_unit {
            get {
                return ResourceManager.GetString("Price of unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підрозділ.
        /// </summary>
        internal static string Sub_department {
            get {
                return ResourceManager.GetString("Sub-department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна вартість.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість замовлення за відділом.
        /// </summary>
        internal static string Total_by_department {
            get {
                return ResourceManager.GetString("Total by department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість замовлення за темою.
        /// </summary>
        internal static string Total_by_fund {
            get {
                return ResourceManager.GetString("Total by fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість замовлення за підрозділом.
        /// </summary>
        internal static string Total_by_sub_department {
            get {
                return ResourceManager.GetString("Total by sub-department", resourceCulture);
            }
        }
    }
}
