//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promasy.Domain.Resources.Organizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CityType_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CityType_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Promasy.Domain.Resources.Organizations.CityType.uk", typeof(CityType_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to місто.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м..
        /// </summary>
        internal static string City_Short {
            get {
                return ResourceManager.GetString("City.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to селище.
        /// </summary>
        internal static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с-ще.
        /// </summary>
        internal static string Settlement_Short {
            get {
                return ResourceManager.GetString("Settlement.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to селище міського типу.
        /// </summary>
        internal static string UrbanVillage {
            get {
                return ResourceManager.GetString("UrbanVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to смт.
        /// </summary>
        internal static string UrbanVillage_Short {
            get {
                return ResourceManager.GetString("UrbanVillage.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to село.
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с..
        /// </summary>
        internal static string Village_Short {
            get {
                return ResourceManager.GetString("Village.Short", resourceCulture);
            }
        }
    }
}
