//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promasy.Domain.Resources.Organizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StreetType_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StreetType_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Promasy.Domain.Resources.Organizations.StreetType.uk", typeof(StreetType_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проспект.
        /// </summary>
        internal static string Avenue {
            get {
                return ResourceManager.GetString("Avenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to просп..
        /// </summary>
        internal static string Avenue_Short {
            get {
                return ResourceManager.GetString("Avenue.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to завулок.
        /// </summary>
        internal static string BackValley {
            get {
                return ResourceManager.GetString("BackValley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тупик.
        /// </summary>
        internal static string BlindValley {
            get {
                return ResourceManager.GetString("BlindValley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бульвар.
        /// </summary>
        internal static string Boulevard {
            get {
                return ResourceManager.GetString("Boulevard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бульв.
        /// </summary>
        internal static string Boulevard_Short {
            get {
                return ResourceManager.GetString("Boulevard.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to заїзд.
        /// </summary>
        internal static string Bout {
            get {
                return ResourceManager.GetString("Bout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to роз&apos;їзд.
        /// </summary>
        internal static string Crossing {
            get {
                return ResourceManager.GetString("Crossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to узвіз.
        /// </summary>
        internal static string Descent {
            get {
                return ResourceManager.GetString("Descent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в&apos;їзд.
        /// </summary>
        internal static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to просіка.
        /// </summary>
        internal static string Glade {
            get {
                return ResourceManager.GetString("Glade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шосе.
        /// </summary>
        internal static string Highway {
            get {
                return ResourceManager.GetString("Highway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to провулок.
        /// </summary>
        internal static string Lane {
            get {
                return ResourceManager.GetString("Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пров..
        /// </summary>
        internal static string Lane_Short {
            get {
                return ResourceManager.GetString("Lane.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лінія.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мікрорайон.
        /// </summary>
        internal static string MicroDistrict {
            get {
                return ResourceManager.GetString("MicroDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м-р.
        /// </summary>
        internal static string MicroDistrict_Short {
            get {
                return ResourceManager.GetString("MicroDistrict.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проїзд.
        /// </summary>
        internal static string Passage {
            get {
                return ResourceManager.GetString("Passage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to квартал.
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to набережна.
        /// </summary>
        internal static string Quay {
            get {
                return ResourceManager.GetString("Quay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to площа.
        /// </summary>
        internal static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вулиця.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вул.
        /// </summary>
        internal static string Street_Short {
            get {
                return ResourceManager.GetString("Street.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to алея.
        /// </summary>
        internal static string Valley {
            get {
                return ResourceManager.GetString("Valley", resourceCulture);
            }
        }
    }
}
