//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promasy.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Promasy.Core.Resources.Resources.SharedResource.uk", typeof(SharedResource_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обраний тип міста не існує.
        /// </summary>
        internal static string City_type_does_not_exist {
            get {
                return ResourceManager.GetString("City type does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPV код має бути у форматі 12345678-9 .
        /// </summary>
        internal static string CPV_code_must_be_in_format_12345678_9 {
            get {
                return ResourceManager.GetString("CPV code must be in format 12345678-9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відділ не існує.
        /// </summary>
        internal static string Department_does_not_exist {
            get {
                return ResourceManager.GetString("Department does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відділ має підрозділи.
        /// </summary>
        internal static string Department_has_subdepartments {
            get {
                return ResourceManager.GetString("Department has subdepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірно вказано ІД відділу.
        /// </summary>
        internal static string Incorrect_department_id {
            get {
                return ResourceManager.GetString("Incorrect department id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірно вказано ІД.
        /// </summary>
        internal static string Incorrect_Id {
            get {
                return ResourceManager.GetString("Incorrect Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірно вказано ІД організації.
        /// </summary>
        internal static string Incorrect_organization_id {
            get {
                return ResourceManager.GetString("Incorrect organization id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильне ім&apos;я користувача або пароль.
        /// </summary>
        internal static string Incorrect_username_or_password {
            get {
                return ResourceManager.GetString("Incorrect username or password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Елемент не існує.
        /// </summary>
        internal static string Item_not_exist {
            get {
                return ResourceManager.GetString("Item not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виробник вже асоційований з замовленням.
        /// </summary>
        internal static string Manufacturer_already_associated_with_order {
            get {
                return ResourceManager.GetString("Manufacturer already associated with order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я має бути унікальним.
        /// </summary>
        internal static string Name_must_be_unique {
            get {
                return ResourceManager.GetString("Name must be unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Організація має відділи.
        /// </summary>
        internal static string Organization_already_has_departments {
            get {
                return ResourceManager.GetString("Organization already has departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Організація не існує.
        /// </summary>
        internal static string Organization_does_not_exist {
            get {
                return ResourceManager.GetString("Organization does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обраний тип вулиці не існує.
        /// </summary>
        internal static string Street_type_does_not_exist {
            get {
                return ResourceManager.GetString("Street type does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постачальник вже асоційований з замовленням.
        /// </summary>
        internal static string Supplier_already_associated_with_order {
            get {
                return ResourceManager.GetString("Supplier already associated with order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цільовий елемент має бути відсутнім у списку висхідних елементів.
        /// </summary>
        internal static string Target_must_not_be_included_in_source_list {
            get {
                return ResourceManager.GetString("Target must not be included in source list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неможливо модифікувати пароль іншого користувача.
        /// </summary>
        internal static string Unable_to_modify_other_user_password {
            get {
                return ResourceManager.GetString("Unable to modify other user password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розмірність вже асоційована з замовленням.
        /// </summary>
        internal static string Unit_already_associated_with_order {
            get {
                return ResourceManager.GetString("Unit already associated with order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостатньо прав для цієї дії.
        /// </summary>
        internal static string You_cannot_perform_this_action {
            get {
                return ResourceManager.GetString("You cannot perform this action", resourceCulture);
            }
        }
    }
}
